"""Hand-curated layer on top of the parsed Adobe tables.

Everything a script cannot derive from Adobe's HTML lives here:
  * PAGES       - every official help page used as a source
  * ENRICH      - tier, contexts, description and search aliases per parsed entry
  * KEY_FILLS   - keys that are blank in Adobe's main table, filled from another official page
  * EXTRA       - extra official sources/contexts/notes attached to parsed entries
  * SUPPLEMENT  - shortcuts that Adobe documents in prose on other help pages

Rule: no key combination may appear here unless a verbatim `quote` from the cited
Adobe page backs it. build_shortcuts.py re-checks every quote against the freshly
downloaded page and drops the entry if the quote has disappeared.

Key names: Ctrl Alt Shift (Windows), Ctrl Opt Shift Cmd (macOS, Ctrl = Control),
plus Enter Return Delete Backspace "Forward Delete" Tab Space Esc Home End
"Page Up" "Page Down" Up Down Left Right, single characters, and the pointer
actions Click Double-click Drag Scroll.
"""

BASE = "https://helpx.adobe.com/premiere/desktop/"

# slug -> path below BASE. The slug is also the cached filename in scripts/raw/.
PAGES = {
    "default-keyboard-shortcuts": "get-started/keyboard-shortcuts/default-keyboard-shortcuts.html",
    "tools-panel": "get-started/tour-the-workspace/tools-panel-and-options-panel.html",
    "edit-video": "edit-projects/intro-to-editing/edit-video-in-premiere.html",
    "navigate-sequences": "edit-projects/change-clip-sequence/navigate-sequences-in-the-timeline.html",
    "play-source": "render-and-export/render-sequences-for-playback/play-clips-in-source-monitor.html",
    "play-program": "render-and-export/render-sequences-for-playback/play-active-sequence-in-program-monitor.html",
    "preroll": "render-and-export/render-sequences-for-playback/play-clips-with-preroll-and-postroll.html",
    "ripple-edits": "edit-projects/trim-clips/perform-ripple-edits.html",
    "rolling-edits": "edit-projects/trim-clips/perform-rolling-edits.html",
    "slip-edits": "edit-projects/trim-clips/perform-slip-edits.html",
    "slide-edits": "edit-projects/trim-clips/perform-slide-edits.html",
    "rate-stretch": "edit-projects/change-clip-speed/change-clip-speed-and-duration-using-the-rate-stretch-tool.html",
    "freeform-shapes": "add-text-images/draw-objects/create-free-form-shapes-for-masking.html",
    "assign-multiple": "get-started/keyboard-shortcuts/assign-multiple-keyboard-shortcuts-to-a-command.html",
    "multicam-target": "edit-projects/set-up-multi-camera-sequences-for-editing/create-and-edit-a-multi-camera-target-sequence.html",
    "navigate-panels": "get-started/tour-the-workspace/navigate-the-panels.html",
    "full-screen": "get-started/tour-the-workspace/display-any-panel-full-screen.html",
    "print-shortcuts": "get-started/keyboard-shortcuts/print-keyboard-shortcuts.html",
    "dock-panels": "get-started/tour-the-workspace/dock-group-undock-panels.html",
    "keyboard-nav": "get-started/set-up-accessibility-features/navigate-premiere-using-the-keyboard.html",
    "preferences": "get-started/preferences-and-settings/preferences-overview.html",
    "timeline-prefs": "get-started/preferences-and-settings/timeline-preferences.html",
    "icon-view": "get-started/customize-the-project-panel/customize-icon-view-in-project-panel.html",
    "freeform-view": "get-started/customize-the-project-panel/customize-freeform-view-in-project-panel.html",
    "bin-behaviors": "organize-media/file-organization/change-bin-behaviors.html",
    "sequence-settings": "edit-projects/change-clip-sequence/sequence-presets-and-settings.html",
    "select-clips": "edit-projects/change-clip-sequence/select-clips.html",
    "rearrange": "edit-projects/change-clip-sequence/rearrange-clips-on-the-timeline.html",
    "source-patching": "edit-projects/intro-to-editing/add-media-to-the-timeline-using-source-patching.html",
    "cut-clips": "edit-projects/trim-clips/cut-clips.html",
    "release-notes": "whats-new/release-notes.html",
    "reveal-nested": "edit-projects/edit-nested-sequences/reveal-a-clip-in-a-nested-source-sequence.html",
    "match-frame": "render-and-export/render-sequences-for-playback/match-a-frame-with-its-source.html",
    "subclip-timeline": "edit-projects/intro-to-editing/create-a-subclip-from-the-timeline.html",
    "timecode-format": "organize-media/apply-labeling/change-timecode-display-format.html",
    "bezier": "add-video-effects/control-effects-and-transitions-using-keyframes/control-effect-changes-using-bezier-keyframe-interpolation.html",
    "copy-keyframes": "add-video-effects/control-effects-and-transitions-using-keyframes/copy-and-paste-keyframes.html",
    "single-sided": "add-video-effects/apply-video-transitions/apply-single-sided-transitions.html",
    "effect-controls": "add-video-effects/apply-video-effects/adjust-controls-in-the-effect-controls-panel.html",
    "time-remap": "edit-projects/change-clip-speed/change-clip-speed-and-duration-using-time-remapping.html",
    "freeze-remap": "organize-media/file-organization/freeze-a-frame-for-a-portion-of-a-clip-using-time-remapping.html",
    "hs-curves": "correct-color/add-color-effects/correct-color-using-hue-and-saturation-curves.html",
    "masks": "add-video-effects/work-with-masks/modifiers-and-conditions-for-masking.html",
    "captions": "add-text-images/insert-captions/translate-captions.html",
    "clip-grid": "correct-color/color-mode-fundamentals/about-the-clip-grid.html",
    "hud": "correct-color/color-mode-fundamentals/understanding-heads-up-displays.html",
    "color-workflow": "correct-color/color-mode-fundamentals/color-mode-workflow.html",
    "color-tools": "correct-color/color-mode-fundamentals/color-tools-panel-overview.html",
    "trim-mode": "edit-projects/trim-clips/about-trim-mode.html",
    "jkl-trim": "edit-projects/trim-clips/perform-j-k-l-dynamic-trimming-in-trim-mode.html",
    "customize-panels": "get-started/tour-the-workspace/customize-panels.html",
    "add-marker": "organize-media/apply-labeling/add-a-marker-to-a-clip.html",
    "snap-clips": "edit-projects/change-clip-sequence/snap-clips.html",
}


def url(slug):
    return BASE + PAGES[slug]


MAIN = "default-keyboard-shortcuts"


def localized_url(locale):
    return f"https://helpx.adobe.com/{locale}/premiere/desktop/" + PAGES[MAIN]


# Site languages besides English. `adobe` is the helpx locale whose translated shortcut table
# supplies official command names (matched to the English table by row position). Adobe's
# Turkish (tr) and Arabic (sa_ar, ae_ar, mena_ar) pages keep the table in English, so those
# languages keep English command names; descriptions and UI text come from scripts/i18n/<lang>.json.
LANGUAGES = {
    "ru": {"name": "Русский", "dir": "ltr", "adobe": "ru"},
    "de": {"name": "Deutsch", "dir": "ltr", "adobe": "de"},
    "es": {"name": "Español", "dir": "ltr", "adobe": "es"},
    "fr": {"name": "Français", "dir": "ltr", "adobe": "fr"},
    "tr": {"name": "Türkçe", "dir": "ltr", "adobe": None},
    "ar": {"name": "العربية", "dir": "rtl", "adobe": None},
}

# Display order for categories. Parsed headings keep Adobe's wording.
CATEGORY_ORDER = [
    "Playback", "Tools panel",
    "File menu", "Edit menu", "Clip menu", "Sequence menu", "Markers menu",
    "Graphics and Titles menu", "Window menu",
    "Timeline panel", "Project panel", "Program Monitor panel", "Effect Controls panel",
    "Effects panel", "Audio Track Mixer panel", "History panel", "Media Browser panel",
    "Metadata panel",
    "Multi-Camera", "Keyframes & effects", "Masks", "Color mode", "Captions",
    "Workspace", "Startup",
]

# Category tiles are grouped; each tile shows the short name (the group label says "menu"/"panel").
CATEGORY_GROUPS = {
    "menus": ["File menu", "Edit menu", "Clip menu", "Sequence menu", "Markers menu",
              "Graphics and Titles menu", "Window menu"],
    "panels": ["Timeline panel", "Project panel", "Program Monitor panel", "Effect Controls panel",
               "Effects panel", "Audio Track Mixer panel", "History panel", "Media Browser panel", "Metadata panel"],
    "techniques": ["Playback", "Tools panel", "Multi-Camera", "Keyframes & effects", "Masks", "Color mode",
                   "Captions", "Workspace", "Startup"],
}
CATEGORY_SHORT = {
    "File menu": "File", "Edit menu": "Edit", "Clip menu": "Clip", "Sequence menu": "Sequence",
    "Markers menu": "Markers", "Graphics and Titles menu": "Graphics & Titles", "Window menu": "Window",
    "Timeline panel": "Timeline", "Project panel": "Project", "Program Monitor panel": "Program Monitor",
    "Effect Controls panel": "Effect Controls", "Effects panel": "Effects", "Audio Track Mixer panel": "Audio Track Mixer",
    "History panel": "History", "Media Browser panel": "Media Browser", "Metadata panel": "Metadata",
    "Playback": "Playback", "Tools panel": "Tools", "Multi-Camera": "Multi-Camera",
    "Keyframes & effects": "Keyframes & effects", "Masks": "Masks", "Color mode": "Color mode",
    "Captions": "Captions", "Workspace": "Workspace", "Startup": "Startup",
}

# Short intro shown on each category section when grouping by category.
CATEGORY_INTROS = {
    "Playback": "Transport and frame-stepping keys for the Timeline and both monitors.",
    "Tools panel": "Single-key tool switches, per Adobe's editing and trimming guides.",
    "File menu": "Projects, sequences, import and export.",
    "Edit menu": "Undo, clipboard, deleting and selection.",
    "Clip menu": "Clip-level commands: speed, gain, linking, grouping, three-point edits.",
    "Sequence menu": "Cutting, transitions, lift/extract, zoom and captions in the active sequence.",
    "Markers menu": "In/Out points and markers.",
    "Graphics and Titles menu": "New text and shape layers, stacking and layer selection.",
    "Window menu": "Workspaces, panels and maximizing frames.",
    "Timeline panel": "Timeline-only keys and mouse techniques: nudge, slip, slide, track heights.",
    "Project panel": "Navigating, viewing and organizing bins and clips.",
    "Program Monitor panel": "Rulers, guides and nudging graphic objects.",
    "Effect Controls panel": "Keys that work while Effect Controls has focus.",
    "Effects panel": "Custom bins in the Effects panel.",
    "Audio Track Mixer panel": "Keys that work while the Audio Track Mixer has focus.",
    "History panel": "Walk and prune the undo history.",
    "Media Browser panel": "Browse files on disk.",
    "Metadata panel": "Playback while logging metadata.",
    "Multi-Camera": "Live camera switching in multi-camera mode.",
    "Keyframes & effects": "Modifier-click tricks for keyframes, transitions and eyedroppers.",
    "Masks": "Mask drawing and nudging modifiers.",
    "Color mode": "Clip Grid navigation and HUD controls in Color mode.",
    "Captions": "Caption track tricks.",
    "Workspace": "Panel focus, floating windows, dialogs and shortcut export.",
    "Startup": "Keys held while Premiere launches.",
}

TIER_NAMES = {1: "Essential", 2: "Everyday", 3: "Pro", 4: "Hidden gem"}
TIER_INTROS = {
    1: "The daily basics. If you learn nothing else, learn these.",
    2: "Regular workflow moves that pay off on every edit.",
    3: "Power-user moves for precise trimming, nudging and three-point editing.",
    4: "Obscure, panel-specific and modifier tricks most editors never discover.",
}

G = ["Global"]
TL = ["Timeline"]
MON = ["Source Monitor", "Program Monitor", "Timeline"]
PRJ = ["Project"]


def E(tier, contexts, description, *aliases):
    return {"tier": tier, "contexts": contexts, "description": description, "aliases": list(aliases)}


# ---------------------------------------------------------------------------
# Enrichment for entries parsed from the main table, keyed by generated id.
# ---------------------------------------------------------------------------
ENRICH = {
    # File menu
    "new-project": E(2, G, "Creates a new project.", "create project", "start project"),
    "new-sequence": E(2, G, "Creates a new sequence from the New Sequence dialog.", "create sequence", "timeline", "new timeline"),
    "open-project": E(2, G, "Opens an existing project file.", "open", "load project"),
    "close": E(3, G, "Closes the active panel.", "close panel", "close window"),
    "close-project": E(3, G, "Closes the current project.", "close"),
    "save": E(1, G, "Saves the current project.", "save project", "store"),
    "save-as": E(2, G, "Saves the project under a new name.", "save as", "rename project"),
    "save-a-copy": E(3, G, "Saves a copy of the project while you keep working in the original.", "backup", "duplicate project"),
    "import-from-media-browser": E(4, ["Media Browser"], "Imports the files selected in the Media Browser.", "ingest"),
    "import": E(2, G, "Opens the Import dialog to bring media into the project.", "add media", "bring in footage", "ingest"),
    "export-media": E(2, G, "Opens export for the selected sequence or clip.", "render", "export video", "output", "deliver"),
    "send-to-media-encoder": E(3, G, "Sends the selection to Adobe Media Encoder for export.", "ame", "queue", "render queue", "export"),
    "get-media-file-properties-for-selection": E(4, PRJ, "Shows the media file properties of the selected item.", "file info", "properties", "codec"),
    "exit": E(3, G, "Quits Premiere.", "quit", "close app"),
    # Edit menu
    "undo": E(1, G, "Reverses the last action.", "revert", "go back", "oops"),
    "redo": E(1, G, "Reapplies the last undone action.", "undo undo"),
    "cut": E(1, G, "Removes the selection and places it on the clipboard.", "clipboard"),
    "copy": E(1, G, "Copies the selection to the clipboard.", "clipboard", "duplicate"),
    "paste": E(1, G, "Pastes the clipboard contents.", "clipboard"),
    "paste-attributes": E(3, TL, "Pastes chosen attributes (effects, motion, etc.) from a copied clip onto the selected clips.", "copy effects", "paste effects", "transfer effects", "attributes"),
    "clear": E(1, G, "Removes the selected items. In the Timeline, selecting a gap and pressing Delete closes it.", "delete", "remove", "close gap"),
    "ripple-delete": E(2, TL, "Deletes the selection and closes the gap it leaves.", "ripple", "delete and close gap", "remove gap", "close gap"),
    "duplicate": E(3, PRJ, "Duplicates the selected project item.", "copy sequence", "clone"),
    "select-all": E(2, G, "Selects everything in the active panel.", "select everything"),
    "deselect-all": E(2, G, "Deselects everything in the active panel.", "clear selection", "select none"),
    "find": E(3, G, "Opens Find for the active panel.", "search"),
    "edit-original": E(4, ["Project", "Timeline"], "Opens the selected clip in the application that created it.", "external editor", "photoshop"),
    "keyboard-shortcuts": E(3, G, "Opens the Keyboard Shortcuts editor to view and customize shortcuts.", "keyboard", "hotkeys", "customize shortcuts", "keymap"),
    # Clip menu
    "make-subclip": E(3, ["Source Monitor"], "Creates a subclip from the marked In/Out range.", "subclip", "partial clip"),
    "audio-channels": E(4, ["Project", "Timeline"], "Changes the audio channel mapping of the selected clip.", "channel mapping", "mono", "stereo"),
    "audio-gain": E(2, ["Project", "Timeline"], "Adjusts the gain of the selected audio clips.", "volume", "loudness", "normalize", "boost audio"),
    "speed-duration": E(2, ["Project", "Timeline"], "Changes the speed, duration or direction of the selected clip.", "speed", "slow motion", "fast forward", "reverse clip", "retime", "duration"),
    "insert": E(2, ["Source Monitor", "Timeline"], "Inserts the source clip at the playhead on targeted tracks, pushing later clips forward.", "insert edit", "three point edit", "splice"),
    "overwrite": E(2, ["Source Monitor", "Timeline"], "Places the source clip at the playhead, replacing whatever is there.", "overwrite edit", "three point edit", "overlay"),
    "enable": E(3, TL, "Enables or disables the selected clips.", "disable clip", "mute clip", "toggle clip"),
    "link": E(2, TL, "Links or unlinks the selected video and audio clips.", "unlink", "link audio", "separate audio"),
    "group": E(3, TL, "Groups the selected clips.", "group clips"),
    "ungroup": E(3, TL, "Ungroups the selected clips.", "ungroup clips"),
    # Sequence menu
    "render-effects-in-to-out": E(2, ["Timeline", "Program Monitor"], "Renders previews of effects between the In and Out points.", "render", "preview", "red bar", "smooth playback"),
    "match-frame": E(3, ["Timeline", "Program Monitor"], "Opens the source clip in the Source Monitor at the frame under the playhead.", "find source", "source frame", "match"),
    "reverse-match-frame": E(4, ["Source Monitor"], "Moves the sequence playhead to the frame shown in the Source Monitor.", "find in sequence", "match frame back"),
    "add-edit": E(1, TL, "Splits clips on the targeted tracks at the playhead.", "split", "cut", "blade", "cut at playhead", "razor at playhead"),
    "add-edit-to-all-tracks": E(2, TL, "Splits clips on all tracks at the playhead.", "split all", "cut all tracks", "blade all", "razor all"),
    "trim-edit": E(3, ["Timeline", "Program Monitor"], "Enters Trim mode for the selected edit point.", "trim mode", "trim monitor", "precision trim"),
    "extend-selected-edit-to-playhead": E(3, TL, "Moves the selected edit point to the playhead.", "extend edit", "trim to playhead"),
    "apply-video-transition": E(2, TL, "Applies the default video transition at the edit point.", "cross dissolve", "transition", "dissolve"),
    "apply-audio-transition": E(2, TL, "Applies the default audio transition at the edit point.", "crossfade", "audio fade", "constant power"),
    "apply-default-transitions-to-selection": E(2, TL, "Applies the default transitions to the selected clips.", "transitions", "fade", "dissolve all"),
    "lift": E(3, TL, "Removes the In-Out range from targeted tracks and leaves a gap.", "remove range", "lift edit"),
    "extract": E(3, TL, "Removes the In-Out range from targeted tracks and closes the gap.", "remove range", "ripple extract", "extract edit"),
    "zoom-in": E(2, ["Timeline", "Project"], "Zooms in on the Timeline (in the Project panel, zooms the view).", "magnify", "timeline zoom", "plus"),
    "zoom-out": E(2, ["Timeline", "Project"], "Zooms out of the Timeline (in the Project panel, zooms the view).", "timeline zoom", "minus", "zoom to fit"),
    "next-in-sequence": E(4, TL, "Jumps to the next gap in the sequence.", "go to gap", "next gap", "find gap"),
    "previous-in-sequence": E(4, TL, "Jumps to the previous gap in the sequence.", "go to gap", "previous gap", "find gap"),
    "snap-in-timeline": E(2, TL, "Toggles snapping in the Timeline.", "snap", "snapping", "magnet"),
    "make-subsequence": E(4, TL, "Makes a new sequence from the selected clips.", "subsequence", "nest", "new sequence from selection"),
    "add-new-caption-track": E(4, TL, "Adds a new caption track.", "subtitles", "captions", "srt"),
    "add-caption-at-playhead": E(3, TL, "Adds a caption at the playhead.", "subtitle", "caption"),
    "go-to-the-next-caption-segment": E(4, TL, "Moves to the next caption segment.", "next subtitle", "captions"),
    "go-to-the-previous-caption-segment": E(4, TL, "Moves to the previous caption segment.", "previous subtitle", "captions"),
    # Markers menu
    "mark-in": E(1, MON, "Sets an In point at the playhead.", "in point", "set in", "start point"),
    "mark-out": E(1, MON, "Sets an Out point at the playhead.", "out point", "set out", "end point"),
    "mark-clip": E(2, ["Timeline", "Program Monitor"], "Sets In and Out points around the clip at the playhead.", "mark clip", "in out around clip"),
    "mark-selection": E(3, TL, "Sets In and Out points around the selected clips.", "in out selection"),
    "go-to-in": E(2, MON, "Moves the playhead to the In point.", "jump to in"),
    "go-to-out": E(2, MON, "Moves the playhead to the Out point.", "jump to out"),
    "clear-in": E(3, MON, "Removes the In point.", "delete in point"),
    "clear-out": E(3, MON, "Removes the Out point.", "delete out point"),
    "clear-in-and-out": E(2, MON, "Removes both the In and Out points.", "clear in out", "remove in out", "reset marks"),
    "add-marker": E(2, MON, "Adds a marker at the playhead, or to the selected clip.", "marker", "bookmark", "flag", "note"),
    "go-to-next-marker": E(2, MON, "Moves the playhead to the next marker.", "next marker", "jump marker"),
    "go-to-previous-marker": E(2, MON, "Moves the playhead to the previous marker.", "previous marker", "jump marker"),
    "clear-selected-marker": E(3, MON, "Removes the selected marker.", "delete marker", "remove marker"),
    "clear-all-markers": E(3, MON, "Removes all markers.", "delete markers", "remove markers"),
    # Graphics and Titles menu
    "text": E(2, ["Program Monitor", "Timeline"], "Adds a new text layer.", "title", "type", "text tool", "add text", "lower third"),
    "rectangle": E(4, ["Program Monitor", "Timeline"], "Adds a new rectangle shape layer.", "shape", "box"),
    "ellipse": E(4, ["Program Monitor", "Timeline"], "Adds a new ellipse shape layer.", "shape", "circle", "oval"),
    "bring-to-front": E(4, ["Program Monitor"], "Moves the selected graphic layer to the top of the stack.", "arrange", "layer order", "z order"),
    "bring-forward": E(4, ["Program Monitor"], "Moves the selected graphic layer up one level.", "arrange", "layer order"),
    "send-backward": E(4, ["Program Monitor"], "Moves the selected graphic layer down one level.", "arrange", "layer order"),
    "send-to-back": E(4, ["Program Monitor"], "Moves the selected graphic layer to the bottom of the stack.", "arrange", "layer order", "z order"),
    "select-next-layer": E(4, ["Program Monitor"], "Selects the next layer in the graphic.", "graphics layer"),
    "select-previous-layer": E(4, ["Program Monitor"], "Selects the previous layer in the graphic.", "graphics layer"),
    # Window menu
    "workspace-all-panels": E(4, G, "Switches to the All Panels workspace.", "layout", "workspace"),
    "workspace-assembly": E(4, G, "Switches to the Assembly workspace.", "layout", "workspace"),
    "workspace-audio": E(4, G, "Switches to the Audio workspace.", "layout", "workspace", "sound"),
    "workspace-captions-and-graphics": E(4, G, "Switches to the Captions and Graphics workspace.", "layout", "workspace", "titles"),
    "workspace-color": E(4, G, "Switches to the Color workspace.", "layout", "workspace", "lumetri", "grading"),
    "workspace-editing": E(3, G, "Switches to the Editing workspace.", "layout", "workspace"),
    "workspace-effects": E(4, G, "Switches to the Effects workspace.", "layout", "workspace"),
    "workspace-essential": E(4, G, "Switches to the Essential workspace.", "layout", "workspace"),
    "workspace-learning": E(4, G, "Switches to the Learning workspace.", "layout", "workspace", "tutorial"),
    "workspace-reset-to-saved-layout": E(3, G, "Resets the current workspace to its saved layout.", "reset workspace", "fix layout", "restore panels"),
    "maximize-frame": E(2, G, "Maximizes the panel under the pointer; press again to restore it.", "full screen", "fullscreen panel", "maximize panel", "restore frame", "tilde", "backtick", "grave", "accent"),
    "panel-audio-clip-mixer": E(4, G, "Opens or focuses the Audio Clip Mixer.", "open panel", "mixer"),
    "panel-audio-track-mixer": E(4, G, "Opens or focuses the Audio Track Mixer.", "open panel", "mixer"),
    "panel-effect-controls": E(3, G, "Opens or focuses the Effect Controls panel.", "open panel", "motion", "opacity"),
    "panel-effects": E(3, G, "Opens or focuses the Effects panel.", "open panel", "effects browser", "transitions"),
    "panel-media-browser": E(4, G, "Opens or focuses the Media Browser.", "open panel", "files"),
    "panel-program-monitor": E(3, G, "Opens or focuses the Program Monitor.", "open panel", "focus program", "viewer"),
    "panel-projects": E(3, G, "Opens or focuses the Project panel.", "open panel", "focus project", "bin"),
    "panel-source-monitor": E(3, G, "Opens or focuses the Source Monitor.", "open panel", "focus source", "viewer"),
    "panel-timeline": E(3, G, "Opens or focuses the Timeline panel.", "open panel", "focus timeline", "sequence"),
    # Audio Track Mixer panel (Loop is merged with the Metadata panel's Loop)
    "show-hide-tracks": E(4, ["Audio Track Mixer"], "Chooses which tracks appear in the Audio Track Mixer.", "mixer tracks", "hide tracks"),
    "loop": E(4, ["Audio Track Mixer", "Metadata"], "Toggles loop playback while the panel has focus.", "repeat", "cycle"),
    "meter-input-s-only": E(4, ["Audio Track Mixer"], "Meters only the input signal on the mixer's meters.", "input meters", "levels"),
    # Effect Controls panel
    "remove-selected-effect": E(3, ["Effect Controls"], "Removes the selected effect from the clip.", "delete effect", "remove effect"),
    "loop-during-audio-only-playback": E(4, ["Effect Controls"], "Toggles looping during audio-only playback.", "repeat", "loop audio"),
    # Effects panel
    "new-custom-bin": E(4, ["Effects"], "Creates a custom bin in the Effects panel.", "favorites", "effects folder"),
    "delete-custom-item": E(4, ["Effects"], "Deletes the selected custom bin or item.", "remove custom bin"),
    # History panel (Delete is merged with the Project panel's Delete)
    "step-backward": E(4, ["History"], "Steps back one state in the History panel.", "undo", "history"),
    "step-forward": E(4, ["History"], "Steps forward one state in the History panel.", "redo", "history"),
    "delete": E(3, ["History", "Project"], "Deletes the selected history state or project item.", "remove", "trash"),
    # Media Browser panel (Open in Source Monitor is merged with the Project panel's)
    "open-in-source-monitor": E(3, ["Media Browser", "Project"], "Opens the selected clip in the Source Monitor.", "preview clip", "load source"),
    "select-directory-list": E(4, ["Media Browser"], "Moves focus to the Media Browser folder list.", "folders"),
    "select-media-list": E(4, ["Media Browser"], "Moves focus to the Media Browser file list.", "files"),
    # Metadata panel
    "play": E(4, ["Metadata"], "Plays back while the Metadata panel has focus.", "playback", "logging"),
    # Program Monitor panel
    "show-rulers": E(4, ["Program Monitor"], "Shows or hides rulers in the Program Monitor.", "rulers", "guides"),
    "show-guides": E(4, ["Program Monitor"], "Shows or hides guides in the Program Monitor.", "guides", "safe margins"),
    "snap-in-program-monitor": E(4, ["Program Monitor"], "Toggles snapping for objects in the Program Monitor.", "snap graphics", "align"),
    "lock-guides": E(4, ["Program Monitor"], "Locks guides so they can't be moved.", "guides"),
    "nudge-selected-object-up-by-five-frames": E(4, ["Program Monitor"], "Moves the selected object up by a large offset.", "move graphic", "nudge", "position"),
    "nudge-selected-object-right-by-five-frames": E(4, ["Program Monitor"], "Moves the selected object right by a large offset.", "move graphic", "nudge", "position"),
    "nudge-selected-object-left-by-five-frames": E(4, ["Program Monitor"], "Moves the selected object left by a large offset.", "move graphic", "nudge", "position"),
    "nudge-selected-object-down-by-five-frames": E(4, ["Program Monitor"], "Moves the selected object down by a large offset.", "move graphic", "nudge", "position"),
    "nudge-selected-object-up-by-one-frame": E(4, ["Program Monitor"], "Moves the selected object up by one step.", "move graphic", "nudge", "position"),
    "nudge-selected-object-right-by-one-frame": E(4, ["Program Monitor"], "Moves the selected object right by one step.", "move graphic", "nudge", "position"),
    "nudge-selected-object-left-by-one-frame": E(4, ["Program Monitor"], "Moves the selected object left by one step.", "move graphic", "nudge", "position"),
    "nudge-selected-object-down-by-one-frame": E(4, ["Program Monitor"], "Moves the selected object down by one step.", "move graphic", "nudge", "position"),
    # Project panel
    "new-bin": E(2, PRJ, "Creates a new bin.", "folder", "new folder", "organize"),
    "list": E(3, PRJ, "Switches the Project panel to List view.", "list view", "details view"),
    "icon": E(3, PRJ, "Switches the Project panel to Icon view.", "icon view", "thumbnails", "grid view"),
    "hover-scrub": E(4, PRJ, "Turns Hover Scrub of thumbnails on or off.", "skim", "scrub thumbnails", "preview"),
    "delete-selection-with-options": E(4, PRJ, "Deletes the selected items, with extra deletion options.", "delete", "remove"),
    "extend-selection-down": E(4, PRJ, "Extends the selection down.", "multi select"),
    "extend-selection-left": E(4, PRJ, "Extends the selection left.", "multi select"),
    "extend-selection-right": E(4, PRJ, "Extends the selection right.", "multi select"),
    "extend-selection-up": E(4, PRJ, "Extends the selection up.", "multi select"),
    "move-selection-down": E(4, PRJ, "Moves the selection down.", "navigate bin"),
    "move-selection-end": E(4, PRJ, "Moves the selection to the last item.", "navigate bin", "last item"),
    "move-selection-home": E(4, PRJ, "Moves the selection to the first item.", "navigate bin", "first item"),
    "move-selection-left": E(4, PRJ, "Moves the selection left.", "navigate bin"),
    "move-selection-page-down": E(4, PRJ, "Moves the selection down one page.", "navigate bin"),
    "move-selection-page-up": E(4, PRJ, "Moves the selection up one page.", "navigate bin"),
    "move-selection-right": E(4, PRJ, "Moves the selection right.", "navigate bin"),
    "move-selection-up": E(4, PRJ, "Moves the selection up.", "navigate bin"),
    "next-column-field": E(4, PRJ, "Moves to the next column field while editing in List view.", "metadata entry", "rename"),
    "next-row-field": E(4, PRJ, "Moves to the next row field while editing in List view.", "metadata entry", "rename"),
    "previous-column-field": E(4, PRJ, "Moves to the previous column field while editing in List view.", "metadata entry"),
    "previous-row-field": E(4, PRJ, "Moves to the previous row field while editing in List view.", "metadata entry"),
    "thumbnail-size-next": E(4, PRJ, "Steps to the next (larger) thumbnail size.", "bigger thumbnails", "icon size"),
    "thumbnail-size-previous": E(4, PRJ, "Steps to the previous (smaller) thumbnail size.", "smaller thumbnails", "icon size"),
    "toggle-view": E(4, PRJ, "Toggles the Project panel view.", "list icon", "switch view"),
    # Timeline panel
    "clear-selection": E(3, TL, "Removes the selected clips from the Timeline.", "delete clip", "remove clip", "backspace"),
    "decrease-audio-tracks-height": E(4, TL, "Makes audio tracks shorter.", "track height", "collapse tracks", "waveform size"),
    "decrease-video-tracks-height": E(3, TL, "Makes video tracks shorter.", "track height", "collapse tracks"),
    "increase-audio-tracks-height": E(4, TL, "Makes audio tracks taller.", "track height", "expand tracks", "waveform size", "bigger waveform"),
    "increase-video-tracks-height": E(3, TL, "Makes video tracks taller.", "track height", "expand tracks", "thumbnails"),
    "nudge-clip-selection-left-five-frames": E(3, TL, "Moves the selected clips five frames earlier.", "nudge", "move clip", "shift clip"),
    "nudge-clip-selection-left-one-frame": E(3, TL, "Moves the selected clips one frame earlier.", "nudge", "move clip", "shift clip"),
    "nudge-clip-selection-right-five-frames": E(3, TL, "Moves the selected clips five frames later.", "nudge", "move clip", "shift clip"),
    "nudge-clip-selection-right-one-frame": E(3, TL, "Moves the selected clips one frame later.", "nudge", "move clip", "shift clip"),
    "ripple-delete-timeline": E(2, TL, "Deletes the selected clips and closes the gap (Timeline panel binding).", "ripple", "delete and close gap", "remove gap", "close gap"),
    "set-work-area-bar-in-point": E(4, TL, "Sets the start of the work area bar at the playhead.", "work area", "render range"),
    "set-work-area-bar-out-point": E(4, TL, "Sets the end of the work area bar at the playhead.", "work area", "render range"),
    "show-next-screen": E(3, TL, "Scrolls the Timeline one screen to the right.", "scroll right", "page"),
    "show-previous-screen": E(3, TL, "Scrolls the Timeline one screen to the left.", "scroll left", "page"),
    "slide-clip-selection-left-five-frames": E(4, TL, "Slides the selected clip five frames left; neighbours are trimmed to compensate.", "slide", "slide edit"),
    "slide-clip-selection-left-one-frame": E(3, TL, "Slides the selected clip one frame left; neighbours are trimmed to compensate.", "slide", "slide edit"),
    "slide-clip-selection-right-five-frames": E(4, TL, "Slides the selected clip five frames right; neighbours are trimmed to compensate.", "slide", "slide edit"),
    "slide-clip-selection-right-one-frame": E(3, TL, "Slides the selected clip one frame right; neighbours are trimmed to compensate.", "slide", "slide edit"),
    "slip-clip-selection-left-five-frames": E(4, TL, "Slips the clip's In and Out points five frames left without moving it.", "slip", "slip edit"),
    "slip-clip-selection-left-one-frame": E(3, TL, "Slips the clip's In and Out points one frame left without moving it.", "slip", "slip edit"),
    "slip-clip-selection-right-five-frames": E(4, TL, "Slips the clip's In and Out points five frames right without moving it.", "slip", "slip edit"),
    "slip-clip-selection-right-one-frame": E(3, TL, "Slips the clip's In and Out points one frame right without moving it.", "slip", "slip edit"),
}

# Keys Adobe's main table leaves blank. Applied only while the table cell is still empty.
KEY_FILLS = {
    "maximize-frame": {
        "win": [["`"]], "mac": [["`"]],
        "slug": "full-screen",
        "quote": "Press the accent key ( ` ) to maximize the panel.",
        "note": "Adobe's shortcut table leaves this key blank; the ` (accent) key comes from Adobe's \"Display any panel full-screen\" page.",
    },
}

# Extra official backing for parsed entries: more sources, contexts, aliases, or notes
# about disagreements between Adobe pages. Quotes are verified like SUPPLEMENT quotes.
EXTRA = {
    "trim-edit": {
        "slug": "trim-mode", "quote": "To enter Trim mode , select the Program or Timeline panel and press Shift + T .",
        "note": "Adobe's \"About Trim mode\" page says Shift + T without naming a platform; the shortcut table lists Cmd + T on macOS.",
    },
    "slip-clip-selection-left-one-frame": {
        "slug": "slip-edits", "quote": "Windows: Alt + Shift + Left",
        "note": "Adobe's \"Perform slip edits\" page lists Alt + Shift + Left on Windows; the shortcut table (used here) lists Ctrl + Alt + Left.",
    },
    "slip-clip-selection-right-one-frame": {
        "slug": "slip-edits", "quote": "Windows: Alt + Shift + Right",
        "note": "Adobe's \"Perform slip edits\" page lists Alt + Shift + Right on Windows; the shortcut table (used here) lists Ctrl + Alt + Right.",
    },
    "panel-audio-clip-mixer": {
        "slug": "keyboard-nav", "quote": "Audio Clip Mixer panel: Shift-6",
        "note": "Adobe's keyboard-navigation page says Shift + 6; the shortcut table (used here) gives Shift + 9 and assigns Shift + 6 to the Audio Track Mixer.",
    },
    "slide-clip-selection-left-one-frame": {"slug": "slide-edits", "quote": "Slide clip selection left one frame"},
    "hover-scrub": {"slug": "icon-view", "quote": "Turn off Hover Scrub using the Project panel menu or by pressing Shift + H ."},
    "match-frame": {"slug": "match-frame", "quote": "Press F to open the source clip at the matching frame in the Source Monitor ."},
    "keyboard-shortcuts": {"slug": "keyboard-nav", "quote": "Use Ctrl + Alt + K (Windows) or Cmd + Opt + K (macOS) to see all shortcuts for a panel."},
    "close": {"slug": "customize-panels", "quote": "To close a panel, use Ctrl + W (Windows), Command + W (macOS), or the Close button."},
    "clear": {"slug": "edit-video", "quote": "To close a gap between clips, select the gap and press delete ."},
    "mark-in": {"slug": "icon-view", "quote": "Set In and Out points while hover scrubbing by pressing I and O .", "contexts": ["Project"]},
    "mark-out": {"slug": "icon-view", "quote": "Set In and Out points while hover scrubbing by pressing I and O .", "contexts": ["Project"]},
    "add-marker": {"slug": "add-marker", "quote": "Select Markers > Add Marker , or press M on the keyboard."},
    "snap-in-timeline": {"slug": "timeline-prefs", "quote": "Toggle snapping on and off by pressing the S key on the keyboard."},
    "insert": {"slug": "source-patching", "quote": "Select the clip and use the comma ( , ) keyboard shortcut to insert a clip."},
}


def S(id, action, category, contexts, win, mac, tier, description, slug, quote, *aliases, note=None):
    return {
        "id": id, "action": action, "category": category, "contexts": contexts,
        "win": win, "mac": mac, "tier": tier, "description": description,
        "slug": slug, "quote": quote, "aliases": list(aliases), "note": note,
    }


SPACE, ARROWS = [["Space"]], [["Up"], ["Down"], ["Left"], ["Right"]]
PLAY = ["Timeline", "Source Monitor", "Program Monitor"]

# ---------------------------------------------------------------------------
# Shortcuts documented in prose on other official Adobe pages.
# ---------------------------------------------------------------------------
SUPPLEMENT = [
    # Playback
    S("play-stop-toggle", "Play-Stop Toggle", "Playback", PLAY, SPACE, SPACE, 1,
      "Starts or stops playback from the playhead.", "play-program",
      "Press Space or L to begin playback from the current playhead position.",
      "play", "pause", "stop", "spacebar", "preview"),
    S("play-forward", "Play Forward", "Playback", PLAY, [["L"]], [["L"]], 1,
      "Plays forward; press again to shuttle faster.", "play-source",
      "Play forward : Use L once for normal speed.",
      "shuttle right", "jkl", "fast forward", "play"),
    S("play-in-reverse", "Play in Reverse", "Playback", PLAY, [["J"]], [["J"]], 1,
      "Plays backward; press again to shuttle faster in reverse.", "play-source",
      "Play in reverse : Use J once for normal reverse speed.",
      "shuttle left", "jkl", "rewind", "backwards"),
    S("stop-playback", "Stop Playback", "Playback", PLAY, [["K"]], [["K"]], 1,
      "Stops playback; hold it with J or L for slow play.", "play-program",
      "Press Space or K to stop playback.",
      "shuttle stop", "jkl", "pause"),
    S("play-forward-slightly-faster", "Play Forward Slightly Faster", "Playback", PLAY, [["Shift", "L"]], [["Shift", "L"]], 3,
      "Plays forward slightly faster than normal speed.", "play-source",
      "Shift + L for slightly faster playback",
      "shuttle", "speed up", "jkl"),
    S("play-in-reverse-slightly-faster", "Play in Reverse Slightly Faster", "Playback", PLAY, [["Shift", "J"]], [["Shift", "J"]], 3,
      "Plays backward slightly faster than normal speed.", "play-source",
      "Shift + J for slightly faster reverse playback",
      "shuttle", "rewind", "jkl"),
    S("play-forward-slowly", "Play Forward Slowly", "Playback", PLAY, [["K", "L"]], [["K", "L"]], 3,
      "Hold K and L together to creep forward; hold K and tap L to step one frame.", "play-source",
      "Use K + L together to move forward slowly",
      "slow motion playback", "step forward", "frame step", "jkl", "crawl"),
    S("play-in-reverse-slowly", "Play in Reverse Slowly", "Playback", PLAY, [["K", "J"]], [["K", "J"]], 3,
      "Hold K and J together to creep backward; hold K and tap J to step one frame back.", "play-source",
      "use K + J to move backward slowly",
      "slow reverse", "step back", "frame step", "jkl", "crawl"),
    S("step-forward-one-frame", "Step Forward One Frame", "Playback", ["Timeline", "Program Monitor"], [["Right"]], [["Right"]], 1,
      "Moves the playhead one frame forward.", "navigate-sequences",
      "Use the Left or Right arrow keys to move one frame.",
      "next frame", "frame by frame", "arrow", "nudge playhead"),
    S("step-back-one-frame", "Step Back One Frame", "Playback", ["Timeline", "Program Monitor"], [["Left"]], [["Left"]], 1,
      "Moves the playhead one frame back.", "navigate-sequences",
      "Use the Left or Right arrow keys to move one frame.",
      "previous frame", "frame by frame", "arrow", "nudge playhead"),
    S("step-forward-five-frames", "Step Forward Five Frames", "Playback", PLAY, [["Shift", "Right"]], [["Shift", "Right"]], 2,
      "Moves the playhead five frames forward.", "play-source",
      "Use Shift + Right Arrow to step forward five frames",
      "jump frames", "skip forward", "arrow"),
    S("step-back-five-frames", "Step Back Five Frames", "Playback", PLAY, [["Shift", "Left"]], [["Shift", "Left"]], 2,
      "Moves the playhead five frames back.", "play-source",
      "use Shift + Left Arrow to step backward five frames",
      "jump frames", "skip back", "arrow"),
    S("play-around", "Play Around", "Playback", PLAY, [["Shift", "K"]], [["Shift", "K"]], 3,
      "Plays a few seconds before and after the playhead (preroll/postroll).", "preroll",
      "Press Shift + K to play a few seconds before and after the playhead position.",
      "preroll", "postroll", "review cut", "play around playhead"),
    S("play-around-in-to-out", "Play In to Out with Preroll and Postroll", "Playback", PLAY, [["Shift", "Space"]], [["Shift", "Space"]], 3,
      "Plays the In-Out range plus preroll before the In point and postroll after the Out point.", "preroll",
      "To preview around an In and Out point selection instead, press Shift + Space .",
      "preroll", "postroll", "play in to out", "review range"),

    # Tools panel
    S("selection-tool", "Selection Tool", "Tools panel", TL, [["V"]], [["V"]], 1,
      "Switches to the Selection tool, the default tool for selecting and moving clips.", "edit-video",
      "Use V to switch to the Selection tool.",
      "arrow tool", "pointer", "select", "move tool"),
    S("razor-tool", "Razor Tool", "Tools panel", TL, [["C"]], [["C"]], 1,
      "Switches to the Razor tool for cutting clips by clicking.", "edit-video",
      "Use C to switch to the Razor tool.",
      "blade", "cut", "split", "scissors"),
    S("ripple-edit-tool", "Ripple Edit Tool", "Tools panel", TL, [["B"]], [["B"]], 2,
      "Switches to the Ripple Edit tool: trims an edge and closes the gap automatically.", "edit-video",
      "Use B to switch to the Ripple Edit tool.",
      "ripple trim", "trim tool"),
    S("rolling-edit-tool", "Rolling Edit Tool", "Tools panel", TL, [["N"]], [["N"]], 2,
      "Switches to the Rolling Edit tool: moves a cut point between two clips.", "rolling-edits",
      "Use N on your keyboard to activate the Rolling Edit tool.",
      "roll edit", "rolling trim", "move cut"),
    S("rate-stretch-tool", "Rate Stretch Tool", "Tools panel", TL, [["R"]], [["R"]], 3,
      "Switches to the Rate Stretch tool: changes clip speed by dragging its edge.", "rate-stretch",
      "Select the Rate Stretch Tool from the Tools panel or press R on your keyboard.",
      "speed", "retime", "time stretch", "fit to gap"),
    S("slip-tool", "Slip Tool", "Tools panel", TL, [["Y"]], [["Y"]], 3,
      "Switches to the Slip tool: shifts a clip's In and Out points without moving it.", "slip-edits",
      "Press Y on your keyboard to activate the Slip tool.",
      "slip edit", "slip"),
    S("slide-tool", "Slide Tool", "Tools panel", TL, [["U"]], [["U"]], 3,
      "Switches to the Slide tool: moves a clip while trimming its neighbours.", "slide-edits",
      "Press U on the keyboard to activate the Slide tool.",
      "slide edit", "slide"),
    S("pen-tool", "Pen Tool", "Tools panel", ["Timeline", "Program Monitor"], [["P"]], [["P"]], 3,
      "Switches to the Pen tool for keyframes, shapes and mask paths.", "freeform-shapes",
      "Use the Pen Tool (P) to create curves",
      "keyframe tool", "bezier", "draw", "rubber band"),
    S("track-select-backward-tool", "Track Select Backward Tool", "Tools panel", TL, [["Shift", "A"]], [["Shift", "A"]], 4,
      "Switches to the Track Select Backward tool, which selects clips to the left of the click.", "assign-multiple",
      "Delete the assigned shortcut (Shift+A) for the Track Select Backward Tool.",
      "select backward", "track selection", "select everything before"),

    # Multi-Camera
    S("multicam-cut-to-camera", "Cut to Camera 1-9", "Multi-Camera", ["Program Monitor", "Timeline"],
      [[str(n)] for n in range(1, 10)], [[str(n)] for n in range(1, 10)], 3,
      "During multi-camera playback, press a main-keyboard number to cut to that camera.", "multicam-target",
      "While the sequence is playing, press the number key on the main keyboard to cut to the camera with that number.",
      "multicam", "multi-cam", "switch angle", "camera angle", "live switch", "number keys"),

    # Timeline panel: mouse + modifier techniques
    S("select-audio-or-video-only", "Select Only Audio or Video of a Linked Clip", "Timeline panel", TL,
      [["Alt", "Click"]], [["Opt", "Click"]], 3,
      "Selects just the audio or just the video part of a linked clip.", "select-clips",
      "Hold Alt (Windows) or Option (macOS), then select only the audio or video portion of a clip.",
      "unlink temporarily", "select audio only", "select video only", "alt click", "option click"),
    S("add-to-selection", "Add Clips to Selection", "Timeline panel", TL, [["Shift", "Click"]], [["Shift", "Click"]], 2,
      "Adds each clicked clip to the selection.", "select-clips",
      "Hold the Shift key and select each clip to select multiple clips.",
      "multi select", "select multiple", "shift click"),
    S("rearrange-clip", "Rearrange Clip (Insert Move)", "Timeline panel", TL,
      [["Ctrl", "Alt", "Drag"]], [["Opt", "Cmd", "Drag"]], 3,
      "Drags a clip to a new spot and inserts it there; only the destination track shifts.", "rearrange",
      "Use Ctrl + Alt (Windows) or command + option (macOS) and drag and drop it to a new location.",
      "swap clips", "reorder", "insert move", "rearrange"),
    S("insert-while-dragging", "Insert While Dragging", "Timeline panel", TL, [["Ctrl", "Drag"]], [["Cmd", "Drag"]], 3,
      "Hold while dragging a clip into the Timeline to insert instead of overwrite.", "source-patching",
      "You can also press Ctrl (Win) or Command (macOS) to enter Insert mode while dragging a clip.",
      "insert edit", "drag insert"),
    S("snap-playhead", "Snap Playhead to Edits and Markers", "Timeline panel", TL, [["Shift", "Drag"]], [["Shift", "Drag"]], 3,
      "Shift-drag the playhead to snap it to clip edges and markers.", "navigate-sequences",
      "To snap to clip edges and markers, shift-drag the playhead in the Timeline panel.",
      "snap cti", "playhead snapping"),
    S("razor-all-tracks", "Razor Through All Tracks", "Timeline panel", TL, [["Shift", "Click"]], [["Shift", "Click"]], 3,
      "With the Razor tool, splits clips on every track at the clicked spot.", "tools-panel",
      "To split clips in all tracks at that location, Shift -click the spot in any of the clips.",
      "blade all", "cut all tracks", "split all"),
    S("razor-audio-or-video-only", "Razor Only Audio or Video", "Timeline panel", TL, [["Alt", "Click"]], [["Opt", "Click"]], 4,
      "With the Razor tool, splits only the audio or only the video of a linked clip.", "cut-clips",
      "To split only the audio or video portion of linked clips, use Alt -click (Windows) or Option -click (macOS) while working with the Razor tool.",
      "blade audio only", "split video only"),
    S("multi-track-select", "Multi-Track Selection", "Timeline panel", TL, [["Shift", "Click"]], [["Shift", "Click"]], 4,
      "With the Track Selection tool, selects a clip and everything to its right on all tracks.", "tools-panel",
      "To select a clip and all clips to its right in all tracks, Shift -click the clip.",
      "track select forward", "select all after"),
    S("rolling-from-ripple-tool", "Rolling Edit from Ripple Edit Tool", "Timeline panel", TL, [["Ctrl", "Click"]], [["Cmd", "Click"]], 4,
      "With the Ripple Edit tool, click an edit point to switch to a rolling edit.", "rolling-edits",
      "Ctrl -click (Windows) or command -click (macOS) on the edit point with the Ripple Edit tool to bring up the Rolling Edit tool.",
      "roll", "temporary rolling"),
    S("split-edit-trim", "Trim One Side of a Linked Clip", "Timeline panel", TL, [["Alt", "Drag"]], [["Opt", "Drag"]], 3,
      "Trim only the audio or the video of a linked clip, for J-cuts and L-cuts.", "rolling-edits",
      "To trim only one track of a linked clip, use Alt (Windows) or Option (macOS) as you perform a split edit (L-cut or J-cut).",
      "j cut", "l cut", "split edit", "audio lead"),
    S("zoom-timeline-at-cursor", "Zoom Timeline at Cursor", "Timeline panel", TL, [["Alt", "Scroll"]], [["Opt", "Scroll"]], 3,
      "Zooms the Timeline around the mouse position.", "release-notes",
      "Option or Alt + mouse wheel would not zoom the Timeline based on the cursor location.",
      "mouse wheel zoom", "scroll zoom"),
    S("scroll-timeline-vertically", "Scroll Timeline Vertically", "Timeline panel", TL, [["Ctrl", "Scroll"]], [], 4,
      "Windows: switches mouse-wheel scrolling in the Timeline to vertical.", "timeline-prefs",
      "Press the Ctrl key to switch to Vertical scrolling on Windows.",
      "vertical scroll", "mouse wheel"),
    S("open-nested-in-source-monitor", "Open Nested Sequence in Source Monitor", "Timeline panel", TL,
      [["Ctrl", "Double-click"]], [["Cmd", "Double-click"]], 4,
      "Opens a nested sequence in the Source Monitor instead of the Timeline.", "sequence-settings",
      "In the Timeline panel, use Ctrl or Command and double-click a nested sequence.",
      "nest", "nested sequence", "source monitor"),
    S("reveal-nested-sequence", "Reveal Nested Sequence", "Timeline panel", TL,
      [["Ctrl", "Shift", "F"]], [["Shift", "T"]], 4,
      "Opens the source sequence of the nest at the playhead, parked on the same frame.", "reveal-nested",
      "Press Ctrl + Shift + F (Windows) or S hift + T (macOS) to open the source sequence in the Timeline panel",
      "nest", "open nest", "match frame nested",
      note="Adobe's \"Match a frame with its source\" page gives Ctrl + Shift + T on Windows instead."),
    S("drag-subclip-to-bin", "Create Subclip by Dragging", "Timeline panel", ["Timeline", "Project"],
      [["Ctrl", "Drag"]], [["Cmd", "Drag"]], 4,
      "Drag a clip from the sequence into a bin to make a subclip.", "subclip-timeline",
      "Hold Ctrl (Windows) or Command (macOS) on your keyboard and click-drag the clip from the sequence to an open bin in the Project panel.",
      "subclip"),
    S("cycle-timecode-format", "Cycle Timecode Display Format", "Timeline panel", MON,
      [["Ctrl", "Click"]], [["Cmd", "Click"]], 4,
      "Click a timecode display to cycle through the available timecode formats.", "timecode-format",
      "Ctrl -click (Windows) or C ommand -click (macOS) a hot text timecode display to toggle through any available timecode formats.",
      "frames", "feet", "timecode", "frame count"),

    # Project panel
    S("set-poster-frame", "Set Poster Frame", "Project panel", PRJ, [["Shift", "P"]], [["Cmd", "P"]], 4,
      "Sets the clip's Icon view thumbnail to the current frame.", "icon-view",
      "press the Shift + P (Windows) or Command + P (macOS) keys",
      "thumbnail", "poster", "icon"),
    S("clear-poster-frame", "Clear Poster Frame", "Project panel", PRJ, [["Ctrl", "Shift", "P"]], [["Opt", "P"]], 4,
      "Resets the clip's Icon view thumbnail.", "icon-view",
      "To clear the poster frame, press the Ctrl + Shift + P (Windows) or Option + P (macOS) keys.",
      "thumbnail", "poster", "reset thumbnail"),
    S("temporary-hover-scrub", "Temporary Hover Scrub", "Project panel", PRJ, [["Shift"]], [["Shift"]], 4,
      "Hold Shift over a thumbnail to hover scrub while Hover Scrub is off.", "icon-view",
      "Temporarily enable Hover Scrub by holding Shift when it's turned off.",
      "skim", "scrub"),
    S("open-bin-in-place", "Open Bin in Place", "Project panel", PRJ, [["Ctrl", "Double-click"]], [["Cmd", "Double-click"]], 4,
      "Opens a bin inside the current Project panel.", "bin-behaviors",
      "To open a bin in place, Ctrl -double-click (Windows) or Command -double-click (macOS) the bin.",
      "folder", "bin"),
    S("open-bin-floating", "Open Bin in Floating Panel", "Project panel", PRJ, [["Alt", "Double-click"]], [["Opt", "Double-click"]], 4,
      "Opens a bin in its own floating panel.", "bin-behaviors",
      "To open a bin in its own floating panel, Alt -double-click (Windows) or Option -double-click (macOS) the bin.",
      "folder", "bin", "new window"),
    S("open-sequence-in-source-monitor", "Open Sequence in Source Monitor", "Project panel", PRJ,
      [["Ctrl", "Double-click"]], [["Cmd", "Double-click"]], 4,
      "Opens a sequence in the Source Monitor so you can edit from it like a clip.", "sequence-settings",
      "To open a sequence in the Source Monitor , press Ctrl or Command and double-click the sequence in the Project panel.",
      "pancake", "sequence as source", "nest"),
    S("freeform-snap-edges", "Snap Clip Edges (Freeform View)", "Project panel", PRJ, [["Alt", "Drag"]], [["Opt", "Drag"]], 4,
      "In Freeform view, drag a clip so its edge snaps to another clip.", "freeform-view",
      "Press Alt (Windows) or Option (macOS) and drag the clip so that its edge snaps to the edge of another clip.",
      "freeform", "align"),
    S("freeform-zoom", "Zoom Freeform View", "Project panel", PRJ, [["Alt", "Scroll"]], [["Opt", "Scroll"]], 4,
      "Zooms in and out of the Freeform view.", "freeform-view",
      "Hold down the Option (macOS) or Alt (Windows) modifier while scrolling the mouse wheel",
      "freeform", "mouse wheel zoom"),

    # Keyframes & effects
    S("add-keyframe-with-pen", "Add Keyframe on Rubber Band", "Keyframes & effects", ["Timeline"],
      [["Ctrl", "Click"]], [["Cmd", "Click"]], 3,
      "With the Pen tool, click a connector line to add a keyframe.", "tools-panel",
      "Ctrl -click (Windows) or Command -click (macOS) on a connector line to set a keyframe.",
      "volume keyframe", "opacity keyframe", "rubber band", "pen"),
    S("change-keyframe-interpolation", "Change Keyframe Interpolation", "Keyframes & effects", ["Timeline", "Effect Controls"],
      [["Ctrl", "Click"]], [["Cmd", "Click"]], 4,
      "Click a keyframe to switch it between Linear and Bezier-type interpolation.", "bezier",
      "Ctrl -click (Windows) or Command -click (macOS) the keyframe to change it to Linear",
      "bezier", "linear", "ease", "smooth keyframe"),
    S("copy-keyframe-by-dragging", "Copy Keyframe by Dragging", "Keyframes & effects", ["Effect Controls"],
      [["Alt", "Drag"]], [["Opt", "Drag"]], 4,
      "Drag a keyframe in Effect Controls to place a copy at the new time.", "copy-keyframes",
      "hold down the Alt (Windows) or Option (macOS) and drag a keyframe to a new location.",
      "duplicate keyframe"),
    S("single-sided-transition", "Place Single-Sided Transition", "Keyframes & effects", ["Timeline"],
      [["Ctrl", "Drag"]], [["Cmd", "Drag"]], 4,
      "Drag a transition onto a cut to place it on one side only.", "single-sided",
      "To place a transition on a single cut, Ctrl + drag (Windows) or Command + drag (macOS) the transition into the Timeline panel.",
      "start at cut", "end at cut", "transition"),
    S("eyedropper-5x5", "Eyedropper 5 x 5 Sample", "Keyframes & effects", ["Effect Controls"],
      [["Ctrl", "Click"]], [["Cmd", "Click"]], 4,
      "Click with an Eyedropper to sample a 5 x 5 pixel area instead of one pixel.", "effect-controls",
      "Ctrl -clicking (Windows) or Command -clicking (macOS) an Eyedropper tool samples a 5 x 5 pixel area.",
      "color picker", "sample color", "average"),
    S("add-speed-keyframe", "Add Speed Keyframe", "Keyframes & effects", ["Timeline"],
      [["Ctrl", "Click"]], [["Cmd", "Click"]], 4,
      "Click the time-remapping rubber band to add a speed keyframe.", "time-remap",
      "Ctrl -click (Windows) or Command -click (macOS) on the rubber band to create a speed keyframe.",
      "time remapping", "speed ramp", "ramp"),
    S("extend-freeze-hold", "Extend Freeze Hold", "Keyframes & effects", ["Timeline"],
      [["Ctrl", "Alt", "Drag"]], [["Opt", "Cmd", "Drag"]], 4,
      "Drag a speed keyframe horizontally to freeze the frame for longer.", "freeze-remap",
      "Ctrl + Alt -drag (Windows) or Option + Command -drag (macOS) the keyframe horizontally to extend the hold.",
      "freeze frame", "hold frame", "time remapping"),
    S("curves-remove-point", "Remove a Curve Control Point", "Color mode", ["Effect Controls"],
      [["Ctrl", "Click"]], [["Cmd", "Click"]], 4,
      "In Lumetri hue/saturation curves, removes a single control point.", "hs-curves",
      "Remove a single control point",
      "lumetri", "curves", "hue vs sat"),
    S("curves-remove-all", "Remove All Curve Control Points", "Color mode", ["Effect Controls"],
      [["Double-click"]], [["Double-click"]], 4,
      "In Lumetri hue/saturation curves, removes all control points.", "hs-curves",
      "Remove all control points",
      "lumetri", "curves", "reset curve"),

    # Masks
    S("nudge-mask-1px", "Nudge Mask or Control Points 1px", "Masks", ["Program Monitor"], ARROWS, ARROWS, 4,
      "Moves the selected mask or control points by one pixel.", "masks",
      "Nudge Mask or Control Points 1px",
      "mask", "move mask", "arrow"),
    S("nudge-mask-10px", "Nudge Mask or Control Points 10px", "Masks", ["Program Monitor"],
      [["Shift", k[0]] for k in ARROWS], [["Shift", k[0]] for k in ARROWS], 4,
      "Moves the selected mask or control points by ten pixels.", "masks",
      "Nudge Mask or Control Points 10px",
      "mask", "move mask", "arrow"),
    S("object-mask-tool", "Create Object Mask", "Masks", ["Program Monitor"], [], [["Opt", "Cmd", "O"]], 4,
      "Object Mask tool: hover over a subject and click to mask it (Adobe lists the macOS keys only).", "masks",
      "Command + Option + O",
      "ai mask", "subject mask", "rotoscope", "object selection"),
    S("object-mask-change-tool", "Change Object Mask Tool (Rectangle or Lasso)", "Masks", ["Program Monitor"], [], [["Opt", "Cmd", "L"]], 4,
      "Switches the Object Mask tool between Rectangle and Lasso (Adobe lists the macOS keys only).", "masks",
      "Command + Option + L",
      "lasso", "object mask"),
    S("convert-mask-point", "Convert Point to Bezier / Bezier to Point", "Masks", ["Program Monitor"], [["Alt", "Click"]], [["Opt", "Click"]], 4,
      "With the Pen tool, click a mask vertex to toggle between corner and Bezier.", "masks",
      "Convert Point to Bezier/ Bezier to Point",
      "bezier", "mask", "smooth point"),
    S("delete-mask-point", "Delete Mask Control Point", "Masks", ["Program Monitor"], [["Ctrl", "Click"]], [["Cmd", "Click"]], 4,
      "With the Pen tool, click a mask control point to delete it.", "masks",
      "Delete Control Point",
      "mask", "remove vertex"),

    # Color mode
    S("color-go-to-previous-clip", "Go to Previous Clip", "Color mode", ["Color mode"], [["Up"]], [["Up"]], 4,
      "Selects the previous clip in the Clip Grid.", "clip-grid",
      "Select Go to Previous Clip ( Up arrow) or Go to Next Clip ( Down arrow).",
      "clip grid", "grading", "lumetri"),
    S("color-go-to-next-clip", "Go to Next Clip", "Color mode", ["Color mode"], [["Down"]], [["Down"]], 4,
      "Selects the next clip in the Clip Grid.", "clip-grid",
      "Select Go to Previous Clip ( Up arrow) or Go to Next Clip ( Down arrow).",
      "clip grid", "grading", "lumetri"),
    S("hide-hud", "Hide HUD While Adjusting", "Color mode", ["Color mode"], [["H"]], [["H"]], 4,
      "Hold H while adjusting a color control to hide the heads-up display.", "hud",
      "hold the H key down while making the adjustment to temporarily hide the HUD.",
      "heads up display", "overlay", "grading"),
    S("unlatch-color-control", "Accept and Unlatch Color Control", "Color mode", ["Color mode"], [], [["Return"], ["Esc"]], 4,
      "Accepts the adjustment and releases the latched control (Adobe documents the macOS keys).", "color-workflow",
      "(or press Return or Escape ) to unlatch the control",
      "accept", "hud", "grading"),
    S("constrain-color-control", "Lock Color Control to Axis", "Color mode", ["Color mode"], [["Shift", "Drag"]], [["Shift", "Drag"]], 4,
      "Hold Shift while dragging a 2D color control to lock it to one axis.", "color-tools",
      "Press and hold Shift and move in the direction you want to lock to constrain a 2D control",
      "constrain", "axis", "grading"),
    S("color-control-sensitivity", "Change Color Control Sensitivity", "Color mode", ["Color mode"], [], [["Opt", "Drag"]], 4,
      "Hold Option while dragging a color control to change its adjustment speed (Adobe documents the macOS key).", "color-tools",
      "Press and hold Option to alter (either slow down or speed up) the rate of operation for any control",
      "fine adjust", "slow", "grading"),

    # Captions
    S("isolate-caption-track", "Isolate Caption Track", "Captions", ["Timeline"], [["Alt", "Click"]], [["Opt", "Click"]], 4,
      "Click a caption track's visibility toggle to show only that track; repeat to mute it.", "captions",
      "Use the Option + click (macOS) or Alt + click (Windows) keyboard shortcuts to isolate a specific caption track.",
      "subtitles", "solo caption", "translation"),

    # Workspace
    S("next-panel", "Activate Panels in Rotation to the Right", "Workspace", ["Global"],
      [["Ctrl", "Shift", "."]], [["Ctrl", "Shift", "."]], 4,
      "Moves panel focus to the next panel, clockwise.", "navigate-panels",
      "macOS: Use Control + Shift + . (period).",
      "cycle panels", "next panel", "focus", "accessibility"),
    S("previous-panel", "Activate Panels in Rotation to the Left", "Workspace", ["Global"],
      [["Ctrl", "Shift", ","]], [["Ctrl", "Shift", ","]], 4,
      "Moves panel focus to the previous panel, counter-clockwise.", "navigate-panels",
      "macOS: Use Control + Shift + , (comma).",
      "cycle panels", "previous panel", "focus", "accessibility"),
    S("undock-panel", "Undock Panel to Floating Window", "Workspace", ["Global"], [["Ctrl", "Drag"]], [["Cmd", "Drag"]], 4,
      "Drag a panel or group to pull it out into a floating window.", "dock-panels",
      "hold down Ctrl (Windows) or C ommand (macOS) and drag the panel or group from its current location.",
      "float", "detach panel", "second monitor"),
    S("copy-shortcuts-to-clipboard", "Copy Keyboard Shortcuts to Clipboard", "Workspace", ["Global"],
      [["Ctrl", "Shift", "Click"]], [["Shift", "Cmd", "Click"]], 4,
      "Hold while opening Keyboard Shortcuts from the menu to reveal a Copy To Clipboard button.", "print-shortcuts",
      "Windows: Press Ctrl + Shift and go to Edit > Keyboard Shortcuts .",
      "print shortcuts", "export shortcuts", "cheat sheet", "list shortcuts"),
    S("focus-dialog-category-list", "Focus Dialog Category List", "Workspace", ["Dialogs"], [["Ctrl", "Tab"]], [["Ctrl", "Tab"]], 4,
      "In dialogs with a category list (like Keyboard Shortcuts), moves focus to that list.", "keyboard-nav",
      "Use Ctrl + Tab (Windows and macOS) to focus on the category list",
      "accessibility", "dialog", "keyboard navigation"),

    # Startup
    S("reset-preferences-at-launch", "Reset Preferences at Launch", "Startup", ["App launch"], [["Alt"]], [["Opt"]], 4,
      "Hold while Premiere starts to restore default preferences; release at the splash screen.", "preferences",
      "hold down Alt (Windows) or Option (macOS) while the application is starting.",
      "reset prefs", "trash preferences", "fix crash", "troubleshoot"),
    S("reset-preferences-and-plugin-cache", "Reset Preferences and Plug-in Cache at Launch", "Startup", ["App launch"],
      [["Alt", "Shift"]], [["Opt", "Shift"]], 4,
      "Hold while Premiere starts to restore default preferences and clear the plug-in cache.", "preferences",
      "hold down Shift + Alt (Windows) or Shift + Option (macOS) while the application is starting.",
      "reset prefs", "plugin cache", "fix crash", "troubleshoot"),
]
